### ISSUE TITLE
Flexiable use of oosse

### ISSUE THREAD

**Issue by Shuwen-Liu** [sthawinke/oosse#2]
Dear oosse team,

I come from you paper and am really interesed in using out-of-sample R2. However, I'm somehow new to R and thus I used my machine learning model in python, but oosee only accept constructing model and prediction in R. I wonder if you could kindly provide a flexiable calculation of out-of-sample R2, for example, I could feed a csv like this to your function and return out-of-sample R2.

| fold   | y_true | y_pred |
|--------|--------|--------|
| fold_1 | 1      | 1.1    |
| fold_2 | 2      | 2.1    |
| fold_3 | 3      | 3.1    |
| ...    | ...    | ...    |

As a non statistic and R specialist, I find diffucult to implement your algorithm by myself, so I reach out to your help and really appreciate it in advance. I would give appropriate citation of your work.

**Comment by sthawinke** [comment]
Dear Siran,

Thanks for your message and your interest in our work. Using the data you show you can calculate an estimate of the out-of-sample R2 as follows:

`dat = read.csv("yourFile.csv");y_pred = dat$y_pred;y_true = dat$y_true`
`MSE = mean((y_pred-y_true)^2)`
`n = length(y_true)`
`margVar  = var(y_true)`
`MST = (n+1)/n*margVar`
`oosR2 = 1-MSE/MST`

Yet for a calculation of the standard error, as in our function oosse::RsquaredSE(), you would need two more components:

 - The standard error on the MSE, obtained either through nested cross-validation or through the bootstrap (the SEMSE argument)
 - An estimate of the correlation between the MSE and MST estimates, obtained through bootstrap or jackknife (the corMSEMST argument)

These components need to be calculated by repeatedly fitting your model, so this you perhaps better do in python. Alternatively, you can try to have the fitFun and predFun functions in the R2oosse() function call your python code directly, then you can use the full functionality of our package.

Hope this helps!
